volumes:
  node_modules:
  minio_storage:

services:
  node:
    build:
      context: .
      target: dev
    container_name: google-dataset
    env_file:
      - .env
    environment: 
      GOOGLE_API_CONCURRENCY: "50"
      MIGRATION_LOG_INPUT_CSV: resources/migration_log_input.csv
    volumes:
      - node_modules:/home/node/node_modules
      - ./build-output/:/home/node/build-output
    ports:
      - "3000:3000" # The app.

  minio:
    container_name: google-dataset-minio
    image: minio/minio
    ports:
      - "9000:9000" # The AWS S3 compatible API.
      - "9001:9001" # The Minio web console.
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 2

  minio-init:
    container_name: google-dataset-minio-init
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      /bin/sh -c "
        mc config host add dataset http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}
        mc mb dataset/${AWS_S3_BUCKET} --ignore-existing
        mc anonymous set download dataset/${AWS_S3_BUCKET};
        exit 0
      "