apiVersion: v1
kind: Secret
metadata:
  name: ${KUBE_NAMESPACE}-secrets
type: Opaque
stringData:
  GOV_NOTIFY_API_KEY: "${GOV_NOTIFY_API_KEY}"
  NOTIFY_EMAIL_TO: "${NOTIFY_EMAIL_TO}"
  SERVICE_ACCOUNT_EMAIL: "${SERVICE_ACCOUNT_EMAIL}"
  AUTH_TOKEN_HASH: "${AUTH_TOKEN_HASH}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${KUBE_NAMESPACE}-base64-secrets
type: Opaque
data:
  SERVICE_ACCOUNT_PRIVATE_KEY: "${SERVICE_ACCOUNT_PRIVATE_KEY_BASE64}"
